apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: 1111-tasks
  name: 1111-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/1111-tasks-dev/1111-tasks:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source
