apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: 852c-tasks
  name: 852c-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/852c-tasks-dev/852c-tasks:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source
