apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tasks
spec:
  port:
    targetPort: 8080
  subdomain: ""
  to:
    kind: Service
    name: tasks-green
    weight: 100
  wildcardPolicy: None