kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    contextDir: homework-private/openshift-tasks
    git:
      uri: "https://github.com/raylaijh/jenkinstest.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
